### ISSUE TITLE
Moving Vert.x repositories into the Eclipse GitHub Organization

### ISSUE THREAD

**Issue by waynebeaton** [vert-x3/eclipse-proposal-wip#5]
> Each existing Vert.x module stays in its own repository and is moved to a Github 
> organization owned by Eclipse. 

We currently only support a single GitHub organization for all Eclipse projects. We expect to move the additional Vert.x repositories into the existing Eclipse organization.

I'll admit that we've been wrestling with whether or not it makes sense to create a separate organization. 

The Eclipse organization is, frankly, a mess and it's difficult to find anything from the organization's landing page. Is it significantly better for the existing Vert.x GitHub organization? i.e. do people actually use the organization landing page to find a repository for a particular functional area?

IMHO, the project website is the right place to point people to the right repository by, for example, providing logical groupings of repositories.

> This repository shall be co-managed by Eclipse 
> and a defined number of the Vert.x/Eclipse team. 

Since committer access to project resources needs to be carefully managed (e.g. we need to ensure that committers have the necessary paperwork in place), Eclipse Foundation staff will take exclusive responsibility for providing management within the organization.

**Comment by Narigo** [comment]
> i.e. do people actually use the organization landing page to find a repository for a particular functional area?

The GitHub repositories are ordered by their last change. I can see what parts of Vert.x changed very quickly by looking at the first page. This helps me finding out if I need to incorporate recent changes in codegen, core or something like sql-common in dependent modules/services/clients/etc.

So yes, at least I am using this page from time to time ;)

**Comment by cescoffier** [comment]
I'm also a power user of the organization page. We have lots of repositories and the fuzzy search field is a must-have feature. I don't want my search result to have items from unrelated projects. 

The ordering is also important. Several times a week, I look at modified repositories to analyse the changes / updates (detect breaking changes, see implications). I could do that looking at the e-mails I receive, but I found the org page much more convenient (Yes, I receive too many e-mails).

About the management of the organization, as soon as the Eclipse maintainers are responsive when we want to create a new repository, a label for issues... it would not be an issue.

**Comment by vietj** [comment]
GitHub provides flexible administration feature that only appears at the organization level based on teams. The team feature allows to share the control between Eclipse and the Project Lead:
- Eclipse is the organization _owner_ : that means only Eclipse can add or remove users at the organization level
- the Project Lead can have less power in a dedicated team that allows him to grant access to a particular repository to a particular user.

I believe this is a good tradeoff that makes everyone happy.

**Comment by purplefox** [comment]
I'd be strongly against moving further Vert.x repositories under the Eclipse organisation.

We have a lot of repositories in Vert.x and it would be a mess to have them all under the eclipse organisation. Personally I use the landing page a lot for searching and I think others do too.

We also use the vert-x3 organisation to manage our teams including the vertx-committers list which does not currently map to the Eclipse committers.

I suggest a better option is to have a new top level organisation for Vert.x which replaces vert-x3 and brings in vertx-core too.

**Comment by michel-kraemer** [comment]
> So yes, at least I am using this page from time to time ;)

+1 me too. I would definitely miss it.

**Comment by maxandersen** [comment]
It is a limitation of github that they can't have sub-organizations; we battled the same thing in our Red Hat and JBoss organizations - current result is a mess of various project and organizations split everywhere :)

I think having something like github.com/eclipse-<toplevel-project> would be the best approach - not just for vert.x, but for any toplevel/notable project organization at eclipse that has the people and community to maintain it. 

(I know that vert.x currently are not an eclipse toplevel project - but I think that is something that would make sense too)

Thus having https://github.com/eclipse-vert.x would make sense to me since it really is its own organization, just like any eclipse toplevel project is its own organization.

We could still have github.com/eclipse contain mirrors of _all_ the various repos to make it even easier to find - but those could then be forks of the github.com/ecipse-vert.x repos.

I think that would make the best of both worlds.

**Comment by purplefox** [comment]
> > I think having something like github.com/eclipse- would be the best approach 

I'd argue that the "eclipse-" part is unnecessary. I don't think it helps the project to have "eclipse" everywhere.

Take a look at google for example. Yes, they have some projects under the "google" organisation but they have others under their own organisation (e.g. kubernetes).

I think Eclipse needs to step away from this "one size fits all", centralised approach and allow projects to flourish without intervening too much. It's the intervention that kills innovation as it means developers waste time on pointless bureacratic tasks instead of developing great software!

**Comment by purplefox** [comment]
Another example is Red Hat - you won't find all Red Hat projects under a common Red Hat organisation.

E.g. 

https://github.com/openshift/
https://github.com/projectodd

(Also note it's not redhat-openshift or redhat-projectodd)

I would say best practice is to allow different github organisations to exist with their own branding.

**Comment by purplefox** [comment]
I think Eclipse needs to come to terms with the fact that a single organisation can own many brands, not just one. In fact, it's pretty unusual for a large organisation to only have one brand!

**Comment by tsegismont** [comment]
+1 on Julien's proposal (keep the vertx org with Eclipse as owner)

Besides, I see no point in adding repositories to the Eclipse GitHub
organization if it is admitted that it is already a mess :)

2016-01-20 11:02 GMT+01:00 Tim Fox notifications@github.com:

**Comment by fjeremic** [comment]
Hi Vert.x team,

I've stumbled onto this thread while investigating the possibility of moving our project, [Eclipse OpenJ9](https://github.com/eclipse/openj9), into its own organization. 

> We also use the vert-x3 organisation to manage our teams including the vertx-committers list which does not currently map to the Eclipse committers.

In particular we are interested in getting a little more control over teams within GitHub. We would like to add non-commiters to a read-only team for the organization so that we can assign issues on GitHub to non-committers.

Do you have any experience with this? How has the transition of Vert.x into its on organization changed things? For better, or for worse? Would love to hear some feedback from you as aim to follow a similar path.

Thanks so much for investing the time to help us.

**Comment by vietj** [comment]
@fjeremic we barely started using a new organisation for eclipse-vertx recently because it took a lot  of time to the foundation to get this approved and technically possible (i.e the foundation scripts that syncs the GitHub organisation took a while to be adapted to custom organisation).

For now the only visible benefit is that we have our own Travis job queue that is not shared with all the other Eclipse projects. We haven't yet leveraged the team aspect yet but as soon as we do we can get back to you.

**Comment by fjeremic** [comment]
Thanks for the swift response. Right! The Travis CI is a nice side-effect of the move. Incidentally I think Eclipse OpenJ9 may have a large blame for consuming so much Travis resource from the Eclipse organization projects, so us moving to a new organization will benefit everyone else.

Looking forward to any updates w.r.t. the team aspect once you get there. Thanks again!
